baseURL = "https://aaubs.github.io/ds23"
staticDir = 'static'
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Social / Business Data Science 2023"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  # editURL = "https://github.com/aaubs/ds23/tree/master/content"
  description = "Social / Business Data Science 2023"
  author = "Roman Jurowetzki & Daniel Hain"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableLanguageSwitchingButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"

[outputs]
home = [ "HTML", "RSS", "JSON"]

#[Languages]
#[Languages.en]
#title = "Documentation for Hugo Learn Theme"
#weight = 1
#languageName = "English"
#landingPageURL = "/en"
#landingPageName = "<i class='fas fa-home'></i> Home"

#[[Languages.en.menu.shortcuts]]
#name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
#identifier = "ds"
#url = "https://github.com/matcornic/hugo-theme-learn"
#weight = 10

[markup.goldmark.renderer]
unsafe = true
